### ISSUE TITLE
[BUG]: Crash when parsing `Optional[Awaitable]`

### ISSUE THREAD

**Issue by JnyJny** [wasi-master/typesplainer#1]
### Description of the bug

I ran `typesplainer` on my code base and it crashed on the type `Optional[Awaitable]`. Using `mypy` on the same file produced no diagnostics indicating a problem with the typing.  I've included a reproducer class and the stack trace in the additional information section. 

### Steps To Reproduce

1. installed from pypi
2. ran on reproducer: `python3 -m typesplainer reproducer.py`
3. _**crash**_

### Additional Information

```python
# reproducer.py
from typing import Awaitable, Optional
class BugClass:
    def no_crash(self) -> Optional[Awaitable[None]]:
        """A method that returns None or an Awaitable"""

    def crashes(self) -> Optional[Awaitable]:
        """A method that returns None or an Awaitable"""
```

```console
$ python3 -m typesplainer reproducer.py 
Optional[Awaitable[None]] (reproducer.py:5:27) : A optional awaitable that returns nothing/none.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ejo/Library/Caches/pypoetry/virtualenvs/busylight-for-humans-gON-ipZ_-py3.9/lib/python3.9/site-packages/typesplainer/__main__.py", line 99, in <module>
    print_description(f.read(), file_name=file)
  File "/Users/ejo/Library/Caches/pypoetry/virtualenvs/busylight-for-humans-gON-ipZ_-py3.9/lib/python3.9/site-packages/typesplainer/__main__.py", line 45, in print_description
    console.print(text, format_location(def_, typehint_text, file_name), ":", describe(def_))
  File "/Users/ejo/Library/Caches/pypoetry/virtualenvs/busylight-for-humans-gON-ipZ_-py3.9/lib/python3.9/site-packages/typesplainer/core.py", line 200, in describe
    return _describe(thing).capitalize() + "."
  File "/Users/ejo/Library/Caches/pypoetry/virtualenvs/busylight-for-humans-gON-ipZ_-py3.9/lib/python3.9/site-packages/typesplainer/core.py", line 47, in _describe
    return f"{'a ' if a else ''}optional {_describe(thing.args[0], a=False, plural=plural)}"
  File "/Users/ejo/Library/Caches/pypoetry/virtualenvs/busylight-for-humans-gON-ipZ_-py3.9/lib/python3.9/site-packages/typesplainer/core.py", line 132, in _describe
    return f"{'a ' if a else ''}awaitable that returns {_describe(thing.args[0])}"
IndexError: tuple index out of range
[VE] ejo@ufo:bl2 -> 

```

**Comment by wasi-master** [comment]
Thanks, I'll look into it!

**Comment by wasi-master** [comment]
[`typing.Awaitable`](https://docs.python.org/3/library/typing.html#typing.Awaitable) seemed to have a required parameter `Generic[T_co]`. Since it's required, I didn't add any checks for it is wasn't used since it should always be used? But after looking at [some examples of Awaitable](https://www.programcreek.com/python/example/94064/typing.Awaitable) it seems like the parameter is optional, which is a bit confusing but I guess it is what it is.

I've also looked at [this StackOverflow question](https://stackoverflow.com/a/59177557/13123877) on how to typehint python async functions, and it states
> ```python
> OnAction = Callable[[Foo, Bar], Awaitable[FooBar]]
> ```
> It is a function that takes Foo, Bar and returns a FooBar

So the parameter is supposed to be it's return type I guess? But how does only `Awaitable` work? I don't know but since it does work I'll fix is asap

**Comment by wasi-master** [comment]
Install version `0.2.5`
